const products = [
    { id: 1, name: "Alpha Premium Hoodie", price: 999, image: "image/alpha1.jpg" },
    { id: 2, name: "Urban Street Jacket", price: 1499, image: "image/alpha2.jpg" },
    { id: 3, name: "Classic Black Tee", price: 499, image: "image/alpha3.jpg" },
    // { id: 4, name: "Oversized Anime Print", price: 699, image: "image/alpha4.png" },
    { id: 5, name: "Tactical Cargo Pants", price: 1299, image: "image/alpha5.jpg" },
    { id: 6, name: "Winter Puffer Jacket", price: 2199, image: "image/alpha6.jpg" },
    { id: 7, name: "Slim Fit Joggers", price: 899, image: "image/alpha7.png" },
    { id: 8, name: "Graphic Sweatshirt", price: 799, image: "image/alpha8.jpg" },
    { id: 9, name: "Vintage Denim Jacket", price: 1799, image: "image/alpha9.png" },
    { id: 10, name: "Street Style Shorts", price: 549, image: "image/alpha10.jpg" },
    { id: 11, name: "Alpha Signature Polo", price: 749, image: "image/alpha11.jpg" },
    { id: 12, name: "Northern Light Windbreaker", price: 1599, image: "image/alpha12.jpg" },
    { id: 13, name: "Solid Cotton Shirt", price: 899, image: "image/alpha13.jpg" },
    { id: 14, name: "Striped Summer Tee", price: 449, image: "image/alpha14.png" },
    { id: 15, name: "Hypebeast Zipper", price: 1199, image: "image/alpha15.jpg" },
    // { id: 16, name: "Relaxed Fit Chinos", price: 1099, image: "image/alpha16.jpg" },
    // { id: 17, name: "Camo Print Hoodie", price: 1049, image: "image/alpha17.jpg" },
    // { id: 18, name: "Basic White Vest", price: 299, image: "image/alpha18.jpg" },
    { id: 19, name: "Athletic Gym Stringer", price: 399, image: "image/alpha19.png" },
    { id: 20, name: "Heavyweight Flannel", price: 1399, image: "image/alpha20.jpg" },
    { id: 21, name: "Alpha Sport Tights", price: 799, image: "image/alpha21.png" },
    // { id: 22, name: "Reflective Night Runner", price: 1699, image: "image/alpha22.png" },
    // { id: 23, name: "Minimalist Gray Hoodie", price: 949, image: "image/alpha23.png" },
    { id: 24, name: "Cyberpunk Techwear Tee", price: 749, image: "image/alpha24.png" },
    { id: 25, name: "Alpha Final Edition Jacket", price: 2999, image: "image/alpha25.jpg" },
    { id: 26, name: "Streetwear Camo Pants", price: 1199, image: "image/alpha26.jpg" },
    { id: 27, name: "Vintage Graphic Tee", price: 549, image: "image/alpha27.png" },
    { id: 28, name: "Alpha Classic Hoodie", price: 899, image: "image/alpha28.png" },
    { id: 29, name: "Urban Camo Jacket", price: 1499, image: "image/alpha29.png" },
    // { id: 30, name: "Basic Cotton Tee", price: 399, image: "image/alpha30.png" },
    // { id: 31, name: "Oversized Anime Hoodie", price: 799, image: "image/alpha31.png" },
    { id: 32, name: "Tactical Cargo Shorts", price: 999, image: "image/alpha32.jpg" },
    { id: 33, name: "Winter Parka Jacket", price: 2499, image: "image/alpha33.png" },
    // { id: 34, name: "Slim Fit Sweatpants", price: 899, image: "image/alpha34.png" },
    // { id: 35, name: "Graphic Pullover Hoodie", price: 799, image: "image/alpha35.jpg" },
    { id: 36, name: "Vintage Denim Vest", price: 1599, image: "image/alpha36.jpg" },
    { id: 37, name: "Street Style Joggers", price: 699, image: "image/alpha37.jpg" },
    // { id: 38, name: "Alpha Signature Tee", price: 499, image: "image/alpha38.jpg" },
    { id: 39, name: "Northern Light Jacket", price: 1799, image: "image/alpha39.png" },
    { id: 40, name: "Solid Cotton Hoodie", price: 999, image: "image/alpha40.png" },

];